services:
  neo4j:
    image: neo4j:latest
    volumes:
        - /$HOME/goinfre/neo4j/logs:/logs
        - /$HOME/goinfre/neo4j/config:/config
        - /$HOME/goinfre/neo4j/data:/data
        - /$HOME/goinfre/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=${database_username}/${database_password}
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always